### ISSUE TITLE
Add DataLoader Class to Populate Sample Data

### ISSUE THREAD

**Issue by nxlsls** [JoghurtCode/CaloCalendar#123]
Summary: Implement a DataLoader class to automatically populate the H2 database with sample data upon application startup. This will aid in development and testing by ensuring consistent initial data.

Details:
	1. User Profiles:
		○ MariusBeier: Male, 30 years, 75 kg, Activity Level 3
		○ MarieKoch: Female, 25 years, 60 kg, Activity Level 2
		○ ThomasMeier: Male, 40 years, 85 kg, Activity Level 4
		○ LaraWage: Female, 35 years, 70 kg, Activity Level 3
		○ MarkHart: Male, 45 years, 90 kg, Activity Level 1
		○ DianaYellow: Female, 28 years, 65 kg, Activity Level 2
		
	2. Grocery Items:
		○ Apple: 95 calories
		○ Banana: 105 calories
		○ Carrot: 41 calories
		○ Steak: 679 calories
		○ Salmon: 208 calories
		○ Broccoli: 55 calories
		○ Orange: 62 calories
		○ Yogurt: 150 calories
		○ Eggs: 78 calories
		○ Rice: 130 calories
		
	3. Meals:
		○ Breakfast: Assigned to MariusBeier
		○ Lunch: Assigned to MarieKoch
		○ Dinner: Assigned to ThomasMeier
		○ Snack: Assigned to MariusBeier
		○ Brunch: Assigned to LaraWage
		○ Late Night Snack: Assigned to DianaYellow
		○ Tea Time: Assigned to MarkHart

Definition of Done:
	• A DataLoader class exists in de.sep.calocalendar.config.
	• The class implements CommandLineRunner to load data on startup.
	• The database is populated with the above sample data upon application start.

**Comment by JoghurtCode** [comment]
Good job with writing this issue @nxlsls 
looks very good 👍
