### ISSUE TITLE
Finish Design Sketch

### ISSUE THREAD

**Issue by JoghurtCode** [JoghurtCode/CaloCalendar#16]
Finish the final Design Sketch for our software

**Comment by YoghurtBaum** [comment]
![Image](https://github.com/JoghurtCode/CaloCalendar/assets/147067192/a2a9d937-cdfb-421e-abac-372b10bb008e)

**Comment by JoghurtCode** [comment]
looks good!

**Comment by JoghurtCode** [comment]
This task is done. Therefore this issue will be closed.
