### ISSUE TITLE
Fetch error response status is 500

### ISSUE THREAD

**Issue by YoghurtBaum** [JoghurtCode/CaloCalendar#50]
Swagger-UI page throwing error

http://localhost:8080/swagger-ui/index.html

![Image](https://github.com/JoghurtCode/CaloCalendar/assets/147067192/9c3ab5db-2a04-49ad-8083-74b23f1117e4)

- Access SwaggerUI page without error

**Comment by JoghurtCode** [comment]
Looks good, I have already merged and reviewed your pull request.
