### ISSUE TITLE
Implement Controller-Tests

### ISSUE THREAD

**Issue by nxlsls** [JoghurtCode/CaloCalendar#52]
We need to write controller tests for the following controllers:

UserProfileController
GroceryItemController
MealController
Definition of Done:

Tests for UserProfileController are implemented
Tests for GroceryItemController are implemented
Tests for MealController are implemented
Each test covers endpoints for creating, retrieving, updating, and deleting entities
The tests validate the correct interaction with service classes
The tests are executed successfully and ensure expected results

**Comment by JoghurtCode** [comment]
This issue is too long. I have manually divided it into 3 smaller issues so each of them can be resolved in a single iteration.
